### PR TITLE
Feature/helpers

### PR DESCRIPTION
**Pull request by seanlin1125**
add helpers file
add req-helper to get req.user in a function way
install imgur, multer and add file-helper to set up imgur logic
add pagination-helper and an example guide below

### CODE REVIEW

**Review by AdrieneTZ — COMMENTED** [review]
- I am confused with this part: in `helpers/pagination-helpers.js`, getPagination function, why `total = 50`? Is this the temporary value?

**Comment by seanlin1125** [comment]
Yes, that just shows you how the args might be
In the example down below the code block, you can see that the getOffset function arguments(i.e limit, page) are not constrainted by any particular numbers
"const page = Number(req.query.page) || 1
const limit = Number(req.query.limit) || DEFAULT_LIMIT
const offset = getOffset(limit, page)"

**Comment by AdrieneTZ** [comment]
Thank you for the detail explanation :)

**Review by AdrieneTZ — APPROVED** [review]
Thank you. This PR is approved!

**Pull request merged**
